"""add click count

Revision ID: 18362df7ffc6
Revises: 006df60bc28f
Create Date: 2026-07-29 11:44:22.504366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18362df7ffc6'
down_revision: Union[str, Sequence[str], None] = '006df60bc28f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('click_count', sa.Integer(), nullable=False,server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'click_count')
    # ### end Alembic commands ###
