"""increase short_code length

Revision ID: 1df209f4ec21
Revises: ea4ce90e2716
Create Date: 2026-07-29 14:41:50.756544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df209f4ec21'
down_revision: Union[str, Sequence[str], None] = 'ea4ce90e2716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'short_code',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('urls', 'short_code',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###
